# config/services.yaml
parameters: { }

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  
  App\Service\MenuExcelReader:
    arguments:
      $projectDir: '%kernel.project_dir%'

  

  App\Service\InfoProvider:
    arguments:
      $projectDir: '%kernel.project_dir%'
  
  App\Service\PersonalizationService: ~

# === Agent Groq ===
  App\Service\GroqOrderAgent:
    arguments:
      $http: '@http_client'
      $apiKey: '%env(GROQ_API_KEY)%'
      $model: '%env(GROQ_MODEL)%'

  App\Service\OrderPayloadGuard: ~
  App\Service\AiOrderMapper: ~

  App\Service\MenuProvider: ~

